//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_customer
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "This Field should not be empty")]
        public string Fname { get; set; }
        [Required(ErrorMessage = "This Field should not be empty")]
        public string Lname { get; set; }
        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Required")]
        [MinLength(10, ErrorMessage = "Mobile no should be 10 digit")]
        public string Mobile { get; set; }
        [Required(ErrorMessage = "This Field should not be empty")]
        public string Addresss { get; set; }
    }
}
